"""Create initial production schema

Revision ID: ca8a064eb00a
Revises: 
Create Date: 2026-03-31 14:08:31.799404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca8a064eb00a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schools_name'), 'schools', ['name'], unique=True)
    op.create_index(op.f('ix_schools_slug'), 'schools', ['slug'], unique=False)
    op.create_table('syllabus_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=64), nullable=False),
    sa.Column('grade', sa.String(length=32), nullable=True),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_syllabus_topics_grade'), 'syllabus_topics', ['grade'], unique=False)
    op.create_index(op.f('ix_syllabus_topics_slug'), 'syllabus_topics', ['slug'], unique=True)
    op.create_index(op.f('ix_syllabus_topics_subject'), 'syllabus_topics', ['subject'], unique=False)
    op.create_table('teacher_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('grade', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_requests_email'), 'teacher_requests', ['email'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('grade', sa.String(length=32), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_subjects', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_school_id'), 'users', ['school_id'], unique=False)
    op.create_table('classrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('grade', sa.String(length=32), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'school_id', 'teacher_id', name='uix_classroom_name_school_teacher')
    )
    op.create_index(op.f('ix_classrooms_grade'), 'classrooms', ['grade'], unique=False)
    op.create_index(op.f('ix_classrooms_school_id'), 'classrooms', ['school_id'], unique=False)
    op.create_index(op.f('ix_classrooms_teacher_id'), 'classrooms', ['teacher_id'], unique=False)
    op.create_table('emotion_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('emotion', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('context', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emotion_logs_emotion'), 'emotion_logs', ['emotion'], unique=False)
    op.create_index(op.f('ix_emotion_logs_timestamp'), 'emotion_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_emotion_logs_user_id'), 'emotion_logs', ['user_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=64), nullable=False),
    sa.Column('grade', sa.String(length=32), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct_index', sa.Integer(), nullable=False),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('syllabus_topic', sa.String(length=128), nullable=True),
    sa.Column('readability_level', sa.String(length=32), nullable=True),
    sa.Column('is_generated', sa.Boolean(), nullable=False),
    sa.Column('generated_by', sa.Integer(), nullable=True),
    sa.Column('generation_meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_difficulty'), 'questions', ['difficulty'], unique=False)
    op.create_index(op.f('ix_questions_generated_by'), 'questions', ['generated_by'], unique=False)
    op.create_index(op.f('ix_questions_grade'), 'questions', ['grade'], unique=False)
    op.create_index(op.f('ix_questions_is_generated'), 'questions', ['is_generated'], unique=False)
    op.create_index(op.f('ix_questions_subject'), 'questions', ['subject'], unique=False)
    op.create_index(op.f('ix_questions_syllabus_topic'), 'questions', ['syllabus_topic'], unique=False)
    op.create_table('subject_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=64), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('best_streak', sa.Integer(), nullable=False),
    sa.Column('total_time_spent', sa.Integer(), nullable=False),
    sa.Column('last_practiced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'subject', name='uix_user_subject_perf')
    )
    op.create_index(op.f('ix_subject_performance_subject'), 'subject_performance', ['subject'], unique=False)
    op.create_index(op.f('ix_subject_performance_user_id'), 'subject_performance', ['user_id'], unique=False)
    op.create_table('tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('subject', sa.String(length=64), nullable=False),
    sa.Column('grade', sa.String(length=32), nullable=False),
    sa.Column('topic', sa.String(length=128), nullable=True),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('time_limit', sa.Integer(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tests_created_by'), 'tests', ['created_by'], unique=False)
    op.create_index(op.f('ix_tests_difficulty'), 'tests', ['difficulty'], unique=False)
    op.create_index(op.f('ix_tests_grade'), 'tests', ['grade'], unique=False)
    op.create_index(op.f('ix_tests_school_id'), 'tests', ['school_id'], unique=False)
    op.create_index(op.f('ix_tests_subject'), 'tests', ['subject'], unique=False)
    op.create_index(op.f('ix_tests_topic'), 'tests', ['topic'], unique=False)
    op.create_table('user_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=64), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('current_difficulty', sa.String(length=16), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'subject', name='uix_user_subject')
    )
    op.create_index(op.f('ix_user_progress_subject'), 'user_progress', ['subject'], unique=False)
    op.create_index(op.f('ix_user_progress_user_id'), 'user_progress', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('settings_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    op.create_table('classroom_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('classroom_id', 'student_id', name='uix_classroom_student')
    )
    op.create_index(op.f('ix_classroom_students_classroom_id'), 'classroom_students', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_classroom_students_student_id'), 'classroom_students', ['student_id'], unique=False)
    op.create_table('test_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('allow_late', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_assignments_assigned_by'), 'test_assignments', ['assigned_by'], unique=False)
    op.create_index(op.f('ix_test_assignments_classroom_id'), 'test_assignments', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_test_assignments_due_at'), 'test_assignments', ['due_at'], unique=False)
    op.create_index(op.f('ix_test_assignments_status'), 'test_assignments', ['status'], unique=False)
    op.create_index(op.f('ix_test_assignments_student_id'), 'test_assignments', ['student_id'], unique=False)
    op.create_index(op.f('ix_test_assignments_test_id'), 'test_assignments', ['test_id'], unique=False)
    op.create_table('test_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_id', 'question_id', name='uix_test_question')
    )
    op.create_index(op.f('ix_test_questions_question_id'), 'test_questions', ['question_id'], unique=False)
    op.create_index(op.f('ix_test_questions_test_id'), 'test_questions', ['test_id'], unique=False)
    op.create_table('test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=64), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('earned_points', sa.Integer(), nullable=False),
    sa.Column('average_time_per_question', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_results_subject'), 'test_results', ['subject'], unique=False)
    op.create_index(op.f('ix_test_results_test_id'), 'test_results', ['test_id'], unique=False)
    op.create_index(op.f('ix_test_results_user_id'), 'test_results', ['user_id'], unique=False)
    op.create_table('answer_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_index', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('time_spent', sa.Integer(), nullable=False),
    sa.Column('difficulty_at_time', sa.String(length=16), nullable=True),
    sa.Column('emotion_at_time', sa.String(length=32), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['test_results.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_logs_answered_at'), 'answer_logs', ['answered_at'], unique=False)
    op.create_index(op.f('ix_answer_logs_question_id'), 'answer_logs', ['question_id'], unique=False)
    op.create_index(op.f('ix_answer_logs_test_id'), 'answer_logs', ['test_id'], unique=False)
    op.create_index(op.f('ix_answer_logs_user_id'), 'answer_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answer_logs_user_id'), table_name='answer_logs')
    op.drop_index(op.f('ix_answer_logs_test_id'), table_name='answer_logs')
    op.drop_index(op.f('ix_answer_logs_question_id'), table_name='answer_logs')
    op.drop_index(op.f('ix_answer_logs_answered_at'), table_name='answer_logs')
    op.drop_table('answer_logs')
    op.drop_index(op.f('ix_test_results_user_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_test_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_subject'), table_name='test_results')
    op.drop_table('test_results')
    op.drop_index(op.f('ix_test_questions_test_id'), table_name='test_questions')
    op.drop_index(op.f('ix_test_questions_question_id'), table_name='test_questions')
    op.drop_table('test_questions')
    op.drop_index(op.f('ix_test_assignments_test_id'), table_name='test_assignments')
    op.drop_index(op.f('ix_test_assignments_student_id'), table_name='test_assignments')
    op.drop_index(op.f('ix_test_assignments_status'), table_name='test_assignments')
    op.drop_index(op.f('ix_test_assignments_due_at'), table_name='test_assignments')
    op.drop_index(op.f('ix_test_assignments_classroom_id'), table_name='test_assignments')
    op.drop_index(op.f('ix_test_assignments_assigned_by'), table_name='test_assignments')
    op.drop_table('test_assignments')
    op.drop_index(op.f('ix_classroom_students_student_id'), table_name='classroom_students')
    op.drop_index(op.f('ix_classroom_students_classroom_id'), table_name='classroom_students')
    op.drop_table('classroom_students')
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_user_progress_user_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_subject'), table_name='user_progress')
    op.drop_table('user_progress')
    op.drop_index(op.f('ix_tests_topic'), table_name='tests')
    op.drop_index(op.f('ix_tests_subject'), table_name='tests')
    op.drop_index(op.f('ix_tests_school_id'), table_name='tests')
    op.drop_index(op.f('ix_tests_grade'), table_name='tests')
    op.drop_index(op.f('ix_tests_difficulty'), table_name='tests')
    op.drop_index(op.f('ix_tests_created_by'), table_name='tests')
    op.drop_table('tests')
    op.drop_index(op.f('ix_subject_performance_user_id'), table_name='subject_performance')
    op.drop_index(op.f('ix_subject_performance_subject'), table_name='subject_performance')
    op.drop_table('subject_performance')
    op.drop_index(op.f('ix_questions_syllabus_topic'), table_name='questions')
    op.drop_index(op.f('ix_questions_subject'), table_name='questions')
    op.drop_index(op.f('ix_questions_is_generated'), table_name='questions')
    op.drop_index(op.f('ix_questions_grade'), table_name='questions')
    op.drop_index(op.f('ix_questions_generated_by'), table_name='questions')
    op.drop_index(op.f('ix_questions_difficulty'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_emotion_logs_user_id'), table_name='emotion_logs')
    op.drop_index(op.f('ix_emotion_logs_timestamp'), table_name='emotion_logs')
    op.drop_index(op.f('ix_emotion_logs_emotion'), table_name='emotion_logs')
    op.drop_table('emotion_logs')
    op.drop_index(op.f('ix_classrooms_teacher_id'), table_name='classrooms')
    op.drop_index(op.f('ix_classrooms_school_id'), table_name='classrooms')
    op.drop_index(op.f('ix_classrooms_grade'), table_name='classrooms')
    op.drop_table('classrooms')
    op.drop_index(op.f('ix_users_school_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_teacher_requests_email'), table_name='teacher_requests')
    op.drop_table('teacher_requests')
    op.drop_index(op.f('ix_syllabus_topics_subject'), table_name='syllabus_topics')
    op.drop_index(op.f('ix_syllabus_topics_slug'), table_name='syllabus_topics')
    op.drop_index(op.f('ix_syllabus_topics_grade'), table_name='syllabus_topics')
    op.drop_table('syllabus_topics')
    op.drop_index(op.f('ix_schools_slug'), table_name='schools')
    op.drop_index(op.f('ix_schools_name'), table_name='schools')
    op.drop_table('schools')
    # ### end Alembic commands ###
